# Workflow for integration

name: Pre-requisites for Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pr_conditions:
    runs-on: ubuntu-latest
    env: |
        USER: test_kkoshy

    steps:
      - name: checking out repository
        uses: actions/checkout@v3

      - name: setting up Python
        uses: actions/setup-python@v3
        
      - name: installing dependencies
        run: |
            echo Python Set up completed...
            echo Installing dependencies...
            python -m pip install flake8 pep8-naming pytest
        
      - name: linting with flake8
        run: |
            echo Checking flake8 competency...
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=100
            
      - name: setting env variables
        run: |
            echo "${{ env.USER }}"

      - name: checking unit tests
        run: |
            echo Running unit tests
            pytest -v -s
